name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # 3. Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4. Run code formatting check
      - name: Run Black (format check)
        run: black --check .

      # 5. Run linting
      - name: Run Flake8
        run: flake8 .

      # 6. Run SQLFluff linting (SQL style check)
      - name: Run SQLFluff
        run: sqlfluff lint .

      # 7. Run unit tests
      - name: Run Pytest
        run: pytest --maxfail=1 --disable-warnings -q

      # 8. (Optional) Validate Airflow DAGs
      - name: Validate Airflow DAGs
        run: |
          python -m airflow dags list || echo "Airflow check skipped"

      # 9. (Optional) Validate dbt project
      - name: Validate dbt project
        run: |
          dbt debug || echo "dbt check skipped"
